name: Build and create release

on:
  workflow_dispatch:

  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          override: true

      - name: Install LLVM
        run: |
          sudo apt update
          sudo apt install llvm

      - name: Build binaries
        run: cargo build --release

      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags')
        with:
          draft: true
          files: target/build/sfm-plus
